### ISSUE TITLE
Conmon Getting Stuck Using 100% CPU

### ISSUE THREAD

**Issue by sstelfox** [containers/conmon#114]
I'm using podman on Fedora 31 as a normal unprivileged user. I've created a pod that contains a fairly restricted elasticsearch, postgresql, and redis instance for development and keep running into a weird issue. When running my unit tests against the services they'll complete once but my system will get incredibly sluggish. top reveals 3 conmon all running at 100% CPU.

At this point there are no connections between anything local on my system, and the three services don't interact with each other. I've confirmed there are no connections with `ss`. Eventually something on my system kills them, the pods, and usually my terminal with it.

This seems like a bug in conmon getting stuck in some kind of spin lock or infinite loop but I don't know enough about the project to attempt to diagnose it. Are there logs or any additional information that I can provide to help diagnose this? Is this even the correct place to report it?

The packaged version on conmon I'm currently using is: conmon-2.0.2-1.fc31.x86_64

**Comment by rlpowell** [comment]
I'm having the exact same issue.

**Comment by haircommander** [comment]
can you try a version with: https://github.com/containers/conmon/pull/90 (v2.0.4 or higher)

**Comment by rlpowell** [comment]
I don't know if this matches your request, but I've restarted and it hasn't come back, and my system is now running:

conmon.x86_64                                                                                            2:2.0.2-1.fc31

Pretty sure I updated that in the meantime.

**Comment by haircommander** [comment]
that's still conmon 2.0.2 unfortunately. 2.0.4 is needed for the fix.

**Comment by sstelfox** [comment]
Looks like the Fedora testing repos jump straight to 2.0.9:

```
dnf list --showduplicates --enablerepo=updates-testing conmon
Last metadata expiration check: 0:12:26 ago on Mon 13 Jan 2020 09:53:34 AM CST.
Installed Packages
conmon.x86_64                     2:2.0.2-1.fc31                     @updates       
Available Packages
conmon.x86_64                     2:2.0.1-1.fc31                     fedora         
conmon.x86_64                     2:2.0.2-1.fc31                     updates        
conmon.x86_64                     2:2.0.9-2.fc31                     updates-testing
```

I'll give that package version a go today and see if I can reproduce it.

**Comment by sstelfox** [comment]
Alright cool. After updating to 2.0.9 I haven't been able to reproduce the issue. Seems like its already been fixed! Just needs to get downstream. Thanks!
