### ISSUE TITLE
Any Statically Linked Pre-Complied Binaray for Download?

### ISSUE THREAD

**Issue by hswong3i** [containers/conmon#120]
Similar as runc (https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc10) and cri-o (https://github.com/cri-o/cri-o/releases/tag/v1.17.0) which now provide pre-complied statically linked binary for download, could we also have that for conmon so simplify the difficulties for cross-OS deployment?

**Comment by rhatdan** [comment]
Please open a PR to make this happen.

**Comment by saschagrunert** [comment]
Right now Cirrus provides a static artifact, like for the latest release here: https://cirrus-ci.com/task/4743976339111936

I put that binary at the release page: https://github.com/containers/conmon/releases/tag/v2.0.10
