### ISSUE TITLE
Ansible Role for conmon

### ISSUE THREAD

**Issue by hswong3i** [containers/conmon#142]
I am now maintenance an Ansible Role for conmon installation (https://github.com/alvistack/ansible-role-conmon), by downloading the static binary release archive and extract it for following OS:
- Ubuntu 16.04/18.04/19.10
- CentOS/RHEL 7/8
- openSUSE 15.1

Could we also introduce this as an alternative installation method, e.g. under https://github.com/containers/conmon/blob/master/install.md#conmon-installation-instructions?

**Comment by haircommander** [comment]
@hswong3i this is awesome, I would be happy to have it added. Do you have interest in submitting a PR?

**Comment by hswong3i** [comment]
> @hswong3i this is awesome, I would be happy to have it added. Do you have interest in submitting a PR?

@haircommander thank you for your interest and PR created (#143) please kindly comment ;-)
