### ISSUE TITLE
add man page

### ISSUE THREAD

**Issue by haircommander** [containers/conmon#184]
conmon could use a man page. while it's not really intended to be called by the end user, other documentation often references to it, like [discussed here](https://github.com/containers/libpod/pull/6666#discussion_r447025534)

**Comment by TomSweeneyRedHat** [comment]
@mheon @baude can you comment on what you'd like to see (or not see) in this man page?  I know you'd some concerns/thoughts in the standup and I want to make sure they're covered here.  I think the main issue was to discourage people from using conmon directly, that its sole design was for use with Podman.   Any other use should not be supportable.

**Comment by mheon** [comment]
We should *not* go into details on arguments and use, IMO. Manpage should make it clear that we do not intend that this be called directly, only by Podman and CRI-O, and that it has been tuned exclusively for those uses.

**Comment by pwFoo** [comment]
Would be nice to know how to use conman. Maybe would be nice for minimal setup of runc / crun direktly with conman

**Comment by rhatdan** [comment]
Conmon has a man page now.  If you want more information on the man page or advanced howtos. PRs welcome.  :^)
