### ISSUE TITLE
podman run --conmon  <path-of-conmon-binary> not working

### ISSUE THREAD

**Issue by pmoogi-redhat** [containers/conmon#217]
I create a custom compiled binary of conmon from conmon latest repo
When using podman with this customer conmon binary using the above command line option, it is not reflecting those changes in the conmon.

podman --version
podman version 2.1.1

Custom conmon binary:
conmon version 2.0.22-dev

**Comment by haircommander** [comment]
hey @pmoogi-redhat when you run podman with `--log-level debug` it shows the conmon path it chose. what is the output of `podman --log-level debug --conmon <path> run alpine ls`

**Comment by pmoogi-redhat** [comment]
it shows /usr/local/libexec/podman/conmon

**Comment by haircommander** [comment]
come to think of it I think it is `podman --conmon ... run...`

**Comment by haircommander** [comment]
also it needs to be a full path for the binary to get picked up, not relative

**Comment by giuseppe** [comment]
yes, the conmon argument must be to podman, not to run:

`podman --conmon /path/to/conmon .. run ..`

I am going to close the issue, please reopen if it still doesn't work
