### ISSUE TITLE
PREFIX is not propagated to docs/Makefile

### ISSUE THREAD

**Issue by chax** [containers/conmon#231]
If i set PREFIX when building, it does not propagate to Makefile for docs, so it installs on default location.
By changing this simple thing, the problem is fixed:

https://github.com/containers/conmon/blob/0331601d5767a3506f5a9c1d03adb44f9b24b94b/docs/Makefile#L1

Change to:
```
PREFIX ?= /usr/local
```

**Comment by rhatdan** [comment]
Could you open a PR to make the change?

**Comment by chax** [comment]
yes
