### ISSUE TITLE
output hanging

### ISSUE THREAD

**Issue by olivier-m** [containers/conmon#236]
Hi,

Since after version 2.0.22 a large amount of data in stdout/stderr hangs the output and all I can do is ctrl+c and podman kill the container.
Here's how to reproduce:

`podman run -rm -ti alpine`

Once in the shell:

`find /`

I also encountered issues with vscode trying to reconnect to a container (it might be related) and failing a lot.
The same steps with 2.0.22 work just fine.

I investigated a little but couldn't find anything, sorry. Might it be related to 0f092d5446fdadb761b8143b5c4b1d1ac9793f29?

**Comment by haircommander** [comment]
@giuseppe can you PTAL

**Comment by justinkb** [comment]
caused by 6287bd884d9bf29e76ac877e0c7e6aad04bc24a4, see my investigation here

https://github.com/containers/podman/issues/9183

reverting it (applies cleanly) fixes the issue entirely

**Comment by giuseppe** [comment]
this part of the code is a mess :(

Opened a PR: https://github.com/containers/conmon/pull/237

**Comment by justinkb** [comment]
I will try your fix later tonight!

**Comment by olivier-m** [comment]
Just tried with 2.0.26 today and it works! Thank you :)
