### ISSUE TITLE
Rename master branch to main branch

### ISSUE THREAD

**Issue by rhatdan** [containers/conmon#259]

**Comment by TomSweeneyRedHat** [comment]
There are a number of links in podman.io, buildah.io and probably buildah, podman and other repositories that will need to be updated after this change as they all have `master` as part of their address.

**Comment by TomSweeneyRedHat** [comment]
oops, ignore my previous dyslexic comment, I thought this came from `containers/common`

**Comment by cevich** [comment]
***Supporting/Required changes:***

- [ ] Update `$CIRRUS_BASE_SHA` value in `contrib/cirrus/lib.sh`
- [ ] Update *master* reference in `contrib/cirrus/lib.sh`

(I'll update this comment as/if I find more)

**Comment by rhatdan** [comment]
@cevich I renamed, but I don't see master in cirrus stuff?

**Comment by cevich** [comment]
There might not be, this repo. is more neglected by me than most others :cry: 

I'll peek and open a PR ad needed, thanks for checking and letting me know.
