### ISSUE TITLE
Seccomp dependency not listed in README

### ISSUE THREAD

**Issue by ThomsonTan** [containers/conmon#285]
Try `make` on a fresh system with the dependencies listed in README installed, and got below error. This could be fixed by running `sudo apt install libseccomp-dev` on debian.

```console
src/seccomp_notify.c:9:10: fatal error: seccomp.h: No such file or directory
    9 | #include <seccomp.h>
      |          ^~~~~~~~~~~
compilation terminated.
```

**Comment by rhatdan** [comment]
Please open a PR to add the dependancy.
