### ISSUE TITLE
Allow For Container Name To Be Shown In Journald 

### ISSUE THREAD

**Issue by p0da** [containers/conmon#293]
**Is this a BUG REPORT or FEATURE REQUEST? (leave only one on its own line)**

/kind feature

**Description**

Would it be possible to add a feature that prefixes journald log messages with the relevant container/tag information? It looks like this exact feature was started in: https://github.com/containers/conmon/pull/273 but never got finished. Thanks.

**Comment by haircommander** [comment]
ah I see, I misunderstood the ask. I have opened https://github.com/containers/conmon/pull/294 to fix. can someone test and let me know if it satisfies their use case?

**Comment by p0da** [comment]
Just updated, feature is working perfectly on my end. Thank you for pushing this feature through @haircommander. Feel free to close this issue as needed.
