### ISSUE TITLE
Please clarify copyright

### ISSUE THREAD

**Issue by bschacht** [containers/conmon#30]
Hi,

the LICENSE file does not specify the copyright holder. https://github.com/containers/conmon/blob/8f7cb2acf5d44141d5433d85e68b43af2895b363/LICENSE#L189 says Copyright {yyyy} {name of copyright owner}. It would be great for downstream packaging to know the correct copyright holder(s).

thanks!

**Comment by vrothberg** [comment]
@rhatdan @mrunalp PTAL

**Comment by rhatdan** [comment]
@vrothberg Do you know what the right thing to do here?  What do most OpenSource projects do?

**Comment by vrothberg** [comment]
@rhatdan, I *think* we can use `Copyright 2018-2019 github.com/containers authors` to have a general and vendor-neutral authority. We could check if other projects are affected as well. The starting date could be the time of creation of the individual repository.

**Comment by rhatdan** [comment]
SGTM

**Comment by haircommander** [comment]
closing per #43
