### ISSUE TITLE
Rust implementation of conmon

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon#307]
We recently discussed the possibilities of re-implementing conmon in Rust. (cc @mrunalp @haircommander)

This issue should be used to gather further pros and cons to find the right move forward.

--- 
Funny enough, I privately started porting conmon to Rust a while ago. I cleaned up the fork and have a diff available here: https://github.com/containers/conmon/compare/main...saschagrunert:rust

It's still using glib, which is something we probably would like to avoid in the future (if we decide to continue the idea).

**Comment by rhatdan** [comment]
Go for it.

**Comment by saschagrunert** [comment]
> @mrunalp made https://github.com/containers/conmon-rs which I think can serve as a place to work on it

Good, let's move issues over there and close this one fow now.

**Comment by tyler92** [comment]
> there would be advantages in having one conmon per pod (podmon grin), and have managers talk to that pod level conmon over some API, rather than execing for each container creation/exec. This will give us savings in long running managers that end up having ballooning rss from concurrent os.Exec() calls

Hi! It sounds great from my point of view. Sorry, I didn't find the right place for my question - are there any plans to implement this feature in C conmon?

**Comment by saschagrunert** [comment]
> > there would be advantages in having one conmon per pod (podmon grin), and have managers talk to that pod level conmon over some API, rather than execing for each container creation/exec. This will give us savings in long running managers that end up having ballooning rss from concurrent os.Exec() calls
> 
> Hi! It sounds great from my point of view. Sorry, I didn't find the right place for my question - are there any plans to implement this feature in C conmon?

Hey, no such enhancements are only planned for the Rust version.
