### ISSUE TITLE
Support `STATUS` sd_notify

### ISSUE THREAD

**Issue by quentin9696** [containers/conmon#311]
/kind feature

**Description**

Support sd_notify `STATUS`

Actually, podman `3.4.1` only support `WATCHDOG` and `READY` notification when using  `--sdnotify=container`. 

That would be interesting to integrate more messages, like `STATUS`

**Comment by vrothberg** [comment]
This is where we had to punch: https://github.com/containers/conmon/blob/main/src/conn_sock.c#L371-L383

@giuseppe WDYT?

**Comment by romge** [comment]
I just spend the whole day finding out, why this is not working, until I found this issue ;)
Any chance this will be implemented?

**Comment by vrothberg** [comment]
@giuseppe WDYT?

**Comment by giuseppe** [comment]
since more users are asking for it, I think at this point it is useful to have it.

Anyone would like to open a PR?
