### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by saschagrunert** [containers/conmon#32]
Hey there :wave:, do we need static binary builds of conmon? We currently have some dependencies in:

```
> ldd bin/conmon
        linux-vdso.so.1 (0x00007fffafde9000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f6325932000)
        libsystemd.so.0 => /usr/lib64/libsystemd.so.0 (0x00007f6325876000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f63256b1000)
        libpcre.so.1 => /usr/lib64/libpcre.so.1 (0x00007f6325621000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f6325600000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f63255f5000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007f63255bc000)
        liblz4.so.1 => /usr/lib64/liblz4.so.1 (0x00007f632559c000)
        libcap.so.2 => /usr/lib64/libcap.so.2 (0x00007f6325595000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f6325569000)
        libgcrypt.so.20 => /usr/lib64/libgcrypt.so.20 (0x00007f6325449000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f6325a76000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f6325444000)
        libgpg-error.so.0 => /usr/lib64/libgpg-error.so.0 (0x00007f632541e000)
```

Feel free to close if this is out of scope.

**Comment by haircommander** [comment]
While I haven't heard of a need, I don't suppose it would hurt :)

**Comment by rhatdan** [comment]
I am fine with adding it,  Seems a lot of people like the idea.

**Comment by saschagrunert** [comment]
I updated the conmon package to 0.2.0 in https://github.com/NixOS/nixpkgs/pull/62213, which can be a good base for static building.

**Comment by saschagrunert** [comment]
This seems really not an easy task because of two huge dependencies: libsystemd and glib2.

I will give an alpinetool chain a try.

**Comment by eriksjolund** [comment]
I found a Dockerfile in 
https://github.com/mgoltzsche/podman-static
and adjusted it a bit
https://github.com/eriksjolund/podman-static/blob/build_conmon_static_experiment/Dockerfile

    $ ldd ./conmon
    	statically linked
    $ ./conmon --version
    conmon version 2.0.0
    commit: e217fdff82e0b1a6184a28c43043a4065083407f
    $ 

It doesn't have systemd but I wonder if systemd is really in use? It seems to be disabled by USE_JOURNALD=0

    $ grep -2 -r '#include <systemd/' .
    ./src/ctr_logging.c-// if the systemd development files were found, we can log to systemd
    ./src/ctr_logging.c-#ifdef USE_JOURNALD
    ./src/ctr_logging.c:#include <systemd/sd-journal.h>
    ./src/ctr_logging.c-#else
    ./src/ctr_logging.c-/* this function should never be used, as journald logging is disabled and
    $ grep USE_JOURNALD= -r .
    ./Makefile:	override CFLAGS += $(shell $(PKG_CONFIG) --cflags libsystemd-journal) -D USE_JOURNALD=0
    ./Makefile:	override CFLAGS += $(shell $(PKG_CONFIG) --cflags libsystemd) -D USE_JOURNALD=0
    $

**Comment by saschagrunert** [comment]
Hey @eriksjolund, yeah systemd might be an issue when it comes to static builds.

**Comment by mgoltzsche** [comment]
FYI: I fixed the static conmon build in https://github.com/mgoltzsche/podman-static (still has no systemd support).
