### ISSUE TITLE
Binaries missing since v2.0.32

### ISSUE THREAD

**Issue by batistein** [containers/conmon#327]
since the release v2.0.32 the binaries for conmon are missing. Is there a particular reason that these are no longer in the releases? I haven't found a hint anywhere.

**Comment by rhatdan** [comment]
I think they used to build them on nix, and the contributor who was doing this work has disappeared.  If you want to manage the nix packaging, then open a PR.

@haircommander Reopen if I am mistaken.

**Comment by haircommander** [comment]
we're still building the nix packages, I have just missed uploading them. I am doing so now, sorry for any inconvenience

**Comment by batistein** [comment]
@rhatdan @haircommander thank you very much for the fast respond! Looking forward for the binaries :)
