### ISSUE TITLE
Journald logging name/tag now mutually exclusive 

### ISSUE THREAD

**Issue by strideynet** [containers/conmon#332]
Hi !

I spotted something which looks like a regression in the behaviour of journald logging between releases v2.0.30 and v2.0.31

https://github.com/containers/conmon/commit/5d5b8536f47f30c28a6821b1b655e450c8b12ce8

This commit appears to change the behaviour unexpectedly. Prior to this commit, if a tag was specified, both CONTAINER_TAG and CONTAINER_NAME would be present, but now, when a tag is specified, only CONTAINER_TAG will be present. If this was intentional, could the reasoning please be explained ?

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by giuseppe** [comment]
that is intentional.  More details are in the discussion here: https://github.com/containers/conmon/issues/301

**Comment by strideynet** [comment]
I am unable to find anything in #301 that explains why CONTAINER_NAME should be dropped when CONTAINER_TAG is provided.

**Comment by haircommander** [comment]
hmm I can't see any reason why we wouldn't print both tag and name if they're both present: https://github.com/containers/conmon/pull/333

**Comment by giuseppe** [comment]
closed by #333

**Comment by rhatdan** [comment]
This means we need a new release of conmon.  @haircommander
