### ISSUE TITLE
journald logging with terminal prints stdin on new lines

### ISSUE THREAD

**Issue by haircommander** [containers/conmon#34]
Based on how runc creates a console socket (only one fd for stdin and stdout), conmon currently isn't correctly figuring out if a character written to a tty is a new stdout line or a character of stdin. As such, it is automatically treated as the former, and running with tty causes odd journald output like:
```
/ #
e
x
i
t

```
Where it should really be
`/ # exit`

when a user types exit into the console.

**Comment by jnovy** [comment]
Closing this one as @haircommander has already merged fix for this some time ago. Please feel free to reopen @haircommander if it is still an issue.

**Comment by haircommander** [comment]
I believe this is still an issue, we referenced this issue in the podman issue but this was never fixed IMO. I don't think it needs to be though if we've gotten away with it this long
