### ISSUE TITLE
2.1.2: Unknown option --log-global-size-max

### ISSUE THREAD

**Issue by babykart** [containers/conmon#345]
Hi,

kubernetes: v1.24.1+k3s1
cri-o: 1.24.1
 
After upgrade to conmon-2.1.2, I experienced errors at starting some pods.
For example _cilium_:

```console
Warning  FailedPostStartHook  50m (x3 over 50m)  kubelet  Exec lifecycle hook ([/cni-install.sh --enable-debug=false --cni-exclusive=true]) for Container "cilium-agent" in Pod "cilium-gqrw9_kube-system(a46e4da4-c3c1-4ea5-89ee-f9d2787bc247)" failed - error: rpc error: code = Unknown desc = command error: EOF, │
│  stdout: conmon: option parsing failed: Unknown option --log-global-size-max
```
Effectivily in `conmon --help`:

```console
<...>
  --log-size-global-max        Maximum size of all log files
<...>
```

Rollback to conmon-2.1.1 fixes the problem.

**Comment by haircommander** [comment]
we have updated conmon-2.1.2 to have the correct flag, sorry for the issues, can you try the new one released today?

**Comment by babykart** [comment]
Thx for you fast reply.
Fixed with new one downloaded today. 👍

**Comment by haircommander** [comment]
glad to hear! I am closing this now
