### ISSUE TITLE
How does conmon rotate files?

### ISSUE THREAD

**Issue by vimalk78** [containers/conmon#367]
I want to understand how does conmon rotate log files, and when does it rotate log files.

In some containers i see log filles like `0.log` , `1.log` , `2.log` , `3.log`  etc
while other containers only have `0.log` and a timestamp based backup file like `0.log.20221230-043744` and `0.log.20221230-005907.gz`

is this difference because of different `kubelet` arguments used to spawn the containers? 

Also, in conmon, `ctr_logging.c` there is logic to check against `log_size_max` and then the existing log file gets renamed to `<old file>.tmp` , but i never see this happening.

I am using openshift 4.11

**Comment by vimalk78** [comment]
checking the node with `oc debug` reveals something interesting

the container where i find `0.log` , `1.log` , `2.log` , `3.log` etc, i see a conmon process with option `-l /var/log/pods/openshift-sdn_sdn-controller-fhfck_06a9cd2f-ec40-4845-a93c-f2bf9c3b7fe8/sdn-controller/3.log`

whereas the one where timestamp based backup log file is present i see `-l /var/log/pods/my-project2_json-log-generator_553ac51c-d606-4f0f-8d9f-112c83f5c4b7/log-generator/0.log`

does presence of `0.log` , `1.log` , `2.log` , `3.log` mean container got restarted? or atleast conmon got restarted? and how?

**Comment by vimalk78** [comment]
I found the answer myself.
The files `0.log` , `1.log` , `2.log` , `3.log` correspond to container restarts.
The log file rotation upon reaching `containerLogMaxSize` is done by renaming the current log file with a timestamp.

I feel so stupid closing this issue.

**Comment by haircommander** [comment]
glad you figured it out! we're all here to learn :smiley:
