### ISSUE TITLE
question about the exit command

### ISSUE THREAD

**Issue by calvin2021y** [containers/conmon#421]
discussions

**Comment by calvin2021y** [comment]
since there is no discussions section, I drop the question here.

The exit command  is always called before the container namespace destroyed ? or some time before some time after?

**Comment by haircommander** [comment]
btw I've enabled discussions!

conmon isn't responsible for destroying container namespaces, that's the responsibility of the higher container manager. The exit command runs after pid 1 of the container exits and conmon is preparing to exit. Thus, assuming whatever entity is calling conmon doesn't try to remove the namespaces before conmon calls the exit command, you should be able to achieve what you're looking for
