### ISSUE TITLE
conmon log file

### ISSUE THREAD

**Issue by haircommander** [containers/conmon#45]
Often, users come with problems that happen in conmon and want to know what is happening. We should allow a --conmon-log-file option for conmon to write to a log file as well as syslog. that way, it will be easier to get the logs from users on non-systemd distributions.

**Comment by rhatdan** [comment]
syslog works on every Unix/Linux System.  No need for systemd.

**Comment by haircommander** [comment]
Ah okay, just a thought but clearly not necessary
