### ISSUE TITLE
Regression (2.1.8 -> 2.1.9)

### ISSUE THREAD

**Issue by cyruseuros** [containers/conmon#477]
Relevant description in this [podman ticket](https://github.com/containers/podman/issues/21024#issuecomment-1857721422)

**Comment by martinetd** [comment]
dup of #475, already fixed in #476 (merged a couple of hours ago, thanks!)
Hopefully we'll get a new tag soon.

**Comment by adelton** [comment]
This seems to be related to, if not outright causing, https://github.com/containers/podman/issues/21051.

**Comment by haircommander** [comment]
this should be fixed by 2.1.10

**Comment by adelton** [comment]
Thanks @haircommander. What is the process / timeline to get the release to https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/amd64/, to get a fix for https://github.com/containers/podman/issues/21051?

**Comment by lauromoura** [comment]
> this should be fixed by 2.1.10

Tried compiling conmon `2.1.10` (hash 2dcd736e46ded79a53339462bc251694b150f870) manually and installing over the debian version[1] while the repository is not updated and indeed the containers are starting fine.

Thanks!

[1] Beware `make install` will default to `/usr/local/bin/conmon` instead of deb's `/usr/bin/conmon`, which is the one pulled by podman.

**Comment by haircommander** [comment]
it should be packaged now!

**Comment by adelton** [comment]
I confirm that [conmon 2.1.10 from https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04](https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/amd64/conmon_2:2.1.10-0ubuntu22.04+obs18.1_amd64.deb) seems to work fine and fixes the https://github.com/containers/podman/issues/21051 problem in my FreeIPA containerization tests.
