### ISSUE TITLE
Use variable for pkg-config

### ISSUE THREAD

**Issue by afbjorklund** [containers/conmon#48]
It would be nice if you could use `$(PKG_CONFIG)` instead of just hard-coding `pkg-config`.

``` sh
sed -e 's/pkg-config/$(PKG_CONFIG)/g' -i Makefile
```

This way it will get the path and flags and other local overrides, it can still default as previous.

``` make
PKG_CONFIG ?= pkg-config
```

**Comment by rhatdan** [comment]
Please open a PR.

**Comment by afbjorklund** [comment]
Will do!
