### ISSUE TITLE
Conmon v2.1.11 missing update to VERSION file

### ISSUE THREAD

**Issue by Inbaraj-S** [containers/conmon#508]
The new release of conmon v2.1.11 is missing an update to VERSION file. Currently it is having value as 2.1.10.
This version file is being used in make file.

**Comment by saschagrunert** [comment]
Hey @Inbaraj-S, thank you for the report! We're aware of this bug and are going to release a new version after https://github.com/containers/conmon/pull/505 got merged to address it.
