### ISSUE TITLE
Signal handlers use not async-signal-safe functions

### ISSUE THREAD

**Issue by iximiuz** [containers/conmon#79]
It seems that at least [`check_child_processes()` ](https://github.com/containers/conmon/blob/19a1d5c48f5c05ec6fb72ec95411e51f25743460/src/conmon.c#L443) can be called as a part of a signal handler. And this function may in turn call [printf-family](https://github.com/containers/conmon/blob/19a1d5c48f5c05ec6fb72ec95411e51f25743460/src/conmon.c#L431) functions, which are not white-listed here http://man7.org/linux/man-pages/man7/signal-safety.7.html. Is it considered a normal practice?

**Comment by giuseppe** [comment]
`check_child_processes` is not called as part of a signal handler, but AFAICS it is called as part of a glib callback.  glib catches the signal then it propagates the signal to the callback(s) as a normal event.  This is the stack trace I see for `check_child_processes` when `SIGUSR1` is received:

```
#0  check_child_processes (pid_to_handler=0x23ee0c0) at src/conmon.c:406
#1  0x00000000004076a9 in on_sigusr1_cb (user_data=<optimized out>) at src/conmon.c:443
#2  0x00007f951a7904a0 in g_main_dispatch (context=0x23f75d0) at ../glib/gmain.c:3179
#3  g_main_context_dispatch (context=context@entry=0x23f75d0) at ../glib/gmain.c:3844
#4  0x00007f951a790830 in g_main_context_iterate (context=0x23f75d0, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at ../glib/gmain.c:3917
#5  0x00007f951a790b23 in g_main_loop_run (loop=0x23f4100) at ../glib/gmain.c:4111
#6  0x00000000004061e4 in main (argc=<optimized out>, argv=<optimized out>) at src/conmon.c
```

differently, `SIGCHLD` gives this stack trace:

```
#0  on_sigchld (signal=17) at src/conmon.c:382
#1  <signal handler called>
#2  0x00007f951a5b9a1f in poll () from target:/lib64/libc.so.6
#3  0x00007f951a79079e in g_main_context_poll (priority=<optimized out>, n_fds=6, fds=0x23f6f00, 
    timeout=<optimized out>, context=0x23f75d0) at ../glib/gmain.c:4216
#4  g_main_context_iterate (context=0x23f75d0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>)
    at ../glib/gmain.c:3912
#5  0x00007f951a790b23 in g_main_loop_run (loop=0x23f4100) at ../glib/gmain.c:4111
#6  0x00000000004061e4 in main (argc=<optimized out>, argv=<optimized out>) at src/conmon.c:1627
```

`on_sigchld()` uses only `raise(3)` which is signal safe.

**Comment by iximiuz** [comment]
Thanks for the nice clarification @giuseppe. I suspect this should be closed then as not an issue.
