### ISSUE TITLE
OOM handling does not work in systemd unified cgroup mode

### ISSUE THREAD

**Issue by filbranden** [containers/conmon#8]
The code opens files `cgroup.event_control` and `memory.oom_control`, which are specific to cgroupv1 only.

Commenting out the only call to `setup_oom_handling()` seems to be enough to make podman/conmon to work on a machine booting with `systemd.unified_cgroup_hierarchy=1`.

So it would be great to update the code to detect and handle cgroupv2 properly (particularly under the unified cgroup, where cgroupv2 is mounted directly under `/sys/fs/cgroup` and cgroupv1 is not available at all.)

Apparently cgroupv2 can do inotify, so maybe doing inotify on `memory.events` and looking for the `oom` or `oom_kill` counters would do the same as the current code? I also found references claiming cgroupv2 can do eventfd as well (though I haven't really found any references to it in the cgroupv2 documentation on the kernel tree.)

Opening this issue to track progress of this feature.

**Comment by rhatdan** [comment]
Thanks @filbranden. @mheon Could you make this change ASAP.

**Comment by mheon** [comment]
Sure, I'll give it a look. I think we'll need a `--cgroups-v2` flag (or similar) to swap the behaviour.

@filbranden Once this is fixed, any other issues with Podman and v2 you find, we'd love to look at. I think we have a pretty good idea of what's broken (stats, maybe pod cgroup creation), but I think you're the first one actually trying it.

**Comment by giuseppe** [comment]
Could we make it automatic?  If we fail to open the cgroupv1 file with ENOENT, then we try with the new file name and set a different handler.

If we can use eventfd, it will be quite straightforward to plug it in the existing code

**Comment by rhatdan** [comment]
Yes we don't want to add a new flag, this should just work.

**Comment by filbranden** [comment]
@mheon Look at this document for detection of cgroup setup:

https://systemd.io/CGROUP_DELEGATION.html#three-different-tree-setups-

See also this commit (in libcontainer, Golang) where I implement this logic over there:

https://github.com/filbranden/runc/commit/2d1d7105b27e7b60a244b8738735dd04e8ce1f97

In short, statfs `/sys/fs/cgroup`, if it's a `cgroup2` mount then use the "unified" logic, otherwise keep the current one.

Thanks a lot for looking into this!

I actually managed to run a simple test (`podman run -t fedora:29 echo "Hello world!"`) when using [this branch of runc](https://github.com/filbranden/runc/commits/systemd2) and commented out this OOM detection in conmon. I still haven't gotten to the other issues (stats, etc.) but I'll probably get there...

My objective now is to get runc/libcontainer working correctly on the unified cgroup tree. In that branch I mentioned I took many shortcuts (such as just bypassing the device cgroup, for instance), I now need to find the proper way to fix that (by passing `DeviceAllow=` options to systemd, etc.) The road ahead is still pretty steep. 😄 

Thanks for all your help once again, I'll keep you in the loop. Please cc me in every issue related to cgroupv2 on OCI containers, as I'm definitely interested.

Cheers!
Filipe

**Comment by haircommander** [comment]
@giuseppe @filbranden is https://github.com/containers/conmon/pull/20/commits/608ea92607cc950721d19ee36f99ddcffb5c1708 sufficient to close this issue?

**Comment by mheon** [comment]
Probably not - we need to actually make it speak V2 so it can appropriately detect OOM there. That commit just removes errors.

**Comment by giuseppe** [comment]
> @giuseppe @filbranden is [608ea92](https://github.com/containers/conmon/commit/608ea92607cc950721d19ee36f99ddcffb5c1708) sufficient to close this issue?

as @mheon said, that commit just removes errors so at least the container can be created in a cgroup v2 environment.

**Comment by giuseppe** [comment]
I've opened a PR here: https://github.com/cri-o/cri-o/pull/2395

I've tested it with crun and Podman on a cgroup v2 system:

```
# podman --runtime /usr/bin/crun run --memory=5M alpine sh -c 'seq 9999999 | /usr/bin/tac'
# podman inspect -l | jq ".[0].State.OOMKilled"
true
```
