### ISSUE TITLE
conmon 2.0.3 breaks container restore in Podman

### ISSUE THREAD

**Issue by adrianreber** [containers/conmon#85]
Starting with the release of conmon 2.0.3 container restoring is broken. I saw it first in CRIU's CI:

https://travis-ci.org/checkpoint-restore/criu/jobs/612285703

Going back to 2.0.2 fixes it. As the CRIU CI setup uses the Ubuntu ppa it would be good to go back to 2.0.2 in the ppa.

**Comment by haircommander** [comment]
I am able to reproduce it, and haven't a clue what's going on. I'll look further.

**Comment by adrianreber** [comment]
I also tested it further and it seems to be related to `winsz`. My guess right now is if the file exists, conmon fails. Not tested, yet.

**Comment by haircommander** [comment]
I don't see the `ctl` fifo after a checkpoint, does podman delete it? if so, it should also delete `winsz`

**Comment by adrianreber** [comment]
Right, that should be an easy fix in Podman. I can open a PR.

**Comment by TomSweeneyRedHat** [comment]
As always, TYVM @adrianreber !

**Comment by haircommander** [comment]
@adrianreber I also have a fix ready if you're busy :smile:

**Comment by adrianreber** [comment]
Yes, please. Next few days would be difficult for me. If you already have the fix, go ahead.

Am 15. November 2019 17:30:49 MEZ schrieb Peter Hunt <notifications@github.com>:

**Comment by adrianreber** [comment]
Closing as it was fixed in Podman.
