### ISSUE TITLE
create_pid not cleaned up on error?

### ISSUE THREAD

**Issue by DaanDeMeyer** [containers/conmon#88]
if this fork succeeds https://github.com/containers/conmon/blob/f6d23b51a3c56cccd4e13b4eea361e98e1855802/src/conmon.c#L1496

And any of the following code before the `waitpid` call fails, shouldn't the child process (`create_pid`) be stopped correctly and waited for with `waitpid`? I think my issue in https://github.com/containers/libpod/issues/3696 is a side effect of an injected fd not being cleaned up correctly when https://github.com/containers/conmon/blob/f6d23b51a3c56cccd4e13b4eea361e98e1855802/src/conmon.c#L1595 fails because of the winsz fix in podman (https://github.com/containers/libpod/pull/4521) not being released yet.

`setup_terminal_control_fifo` calls `exit` when it fails but by then the fd has already been inherited by the child process and because the child process is not cleaned up when `exit` is called, the socket stays open and a subsequent `podman start` fails because the port is already in use.

**Comment by rhatdan** [comment]
@DaanDeMeyer Any chance you could open a PR to fix?

**Comment by DaanDeMeyer** [comment]
I'll take a look when I have time. I'm not entirely sure what signal I should send to stop `create_pid`, if one of the original authors can chime in on that I should be able to figure it out.

**Comment by haircommander** [comment]
I think the classic SIGTERM followed by SIGKILL should suffice. @giuseppe thoughts? Thanks for taking a look and reporting @DaanDeMeyer !

**Comment by DaanDeMeyer** [comment]
Any pointers on the timeout before sending SIGKILL if SIGTERM doesn't work? I think I have the waiting with timeout figured out in [reproc](https://github.com/DaanDeMeyer/reproc/blob/d39b426a2ac663183717ee2b5b564dcb1988b163/reproc/src/posix/process.c#L360) so I was thinking about just reusing that (without the macOS stuff) here if that isn't a problem for you guys.

**Comment by giuseppe** [comment]
I think the `prctl(PR_SET_PDEATHSIG, SIGKILL)` we have in place already ensures the child process is killed when the parent process exits.

There could be a couple of races though that should be verified:

- `PR_SET_PDEATHSIG` called after the parent already exited.
- not waiting that the child process exited.

Does https://github.com/containers/conmon/pull/89 address the issue you are seeing here?

**Comment by DaanDeMeyer** [comment]
It could indeed be a race condition where the parent process exits before `PR_SET_PDEATHSIG` is set. Regardless, #89 is probably an improvement over the current situation just because more stuff that can fail is done before forking instead of after.

#89 should address my issue and `PR_SET_PDEATHSIG` should handle cleanup (apart from the possible race condition) so this can be closed unless you want to keep it open to track the possible race condition.
